// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package dbsqlc

import (
	"context"
)

// iteratorForApplyMigration implements pgx.CopyFromSource.
type iteratorForApplyMigration struct {
	rows                 []ApplyMigrationParams
	skippedFirstNextCall bool
}

func (r *iteratorForApplyMigration) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForApplyMigration) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Version,
		r.rows[0].Name,
		r.rows[0].Namespace,
	}, nil
}

func (r iteratorForApplyMigration) Err() error {
	return nil
}

func (q *Queries) ApplyMigration(ctx context.Context, db DBTX, arg []ApplyMigrationParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"migrations"}, []string{"id", "version", "name", "namespace"}, &iteratorForApplyMigration{rows: arg})
}
