// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conduitmigration struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	Version   string
	Name      string
	Namespace string
}
