// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConduitMigration struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	Version   string
	Name      string
	Namespace string
	Hash      string
}
