// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbsqlc

import (
	"context"
)

const acquireLock = `-- name: AcquireLock :exec
SELECT pg_advisory_lock($1::BIGINT)
`

func (q *Queries) AcquireLock(ctx context.Context, db DBTX, lockNum int64) error {
	_, err := db.Exec(ctx, acquireLock, lockNum)
	return err
}

const allExistingMigrationVersions = `-- name: AllExistingMigrationVersions :many
SELECT version
FROM conduit_migrations
WHERE namespace = $1
ORDER BY version
`

func (q *Queries) AllExistingMigrationVersions(ctx context.Context, db DBTX, namespace string) ([]string, error) {
	rows, err := db.Query(ctx, allExistingMigrationVersions, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applyMigration = `-- name: ApplyMigration :exec
INSERT INTO  conduit_migrations (version, name, namespace)
VALUES ($1, $2, $3)
`

type ApplyMigrationParams struct {
	Version   string
	Name      string
	Namespace string
}

func (q *Queries) ApplyMigration(ctx context.Context, db DBTX, arg ApplyMigrationParams) error {
	_, err := db.Exec(ctx, applyMigration, arg.Version, arg.Name, arg.Namespace)
	return err
}

const doesTableExist = `-- name: DoesTableExist :one
SELECT
  CASE
    WHEN to_regclass($1) IS NULL THEN FALSE
    ELSE TRUE
  END
`

func (q *Queries) DoesTableExist(ctx context.Context, db DBTX, tableName string) (bool, error) {
	row := db.QueryRow(ctx, doesTableExist, tableName)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseLock = `-- name: ReleaseLock :exec
SELECT pg_advisory_unlock($1::BIGINT)
`

func (q *Queries) ReleaseLock(ctx context.Context, db DBTX, lockNum int64) error {
	_, err := db.Exec(ctx, releaseLock, lockNum)
	return err
}

const resetConn = `-- name: ResetConn :exec
RESET ALL
`

func (q *Queries) ResetConn(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, resetConn)
	return err
}

const rollbackMigration = `-- name: RollbackMigration :exec
DELETE FROM conduit_migrations
WHERE version = $1 AND namespace = $2
`

type RollbackMigrationParams struct {
	Version   string
	Namespace string
}

func (q *Queries) RollbackMigration(ctx context.Context, db DBTX, arg RollbackMigrationParams) error {
	_, err := db.Exec(ctx, rollbackMigration, arg.Version, arg.Namespace)
	return err
}
