CREATE TABLE IF NOT EXISTS conduit_migrations (
  id BIGSERIAL NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version VARCHAR(255) NOT NULL,
  name VARCHAR(4095) NOT NULL,
  hash VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  UNIQUE (version)
);
