package conduitcli

import (
	"bytes"
	"context"
	"fmt"
	"io"

	"github.com/jackc/pgx/v5"

	"go.inout.gg/conduit/pkg/buildinfo"
	"go.inout.gg/conduit/pkg/pgdiff"
)

type DumpArgs struct {
	DatabaseURL string
}

func Dump(ctx context.Context, w io.Writer, bi buildinfo.BuildInfo, args DumpArgs) error {
	connConfig, err := pgx.ParseConfig(args.DatabaseURL)
	if err != nil {
		return fmt.Errorf("failed to parse database URL: %w", err)
	}

	stmts, err := pgdiff.DumpSchema(ctx, connConfig)
	if err != nil {
		return fmt.Errorf("failed to dump schema: %w", err)
	}

	var sb bytes.Buffer

	fmt.Fprintf(&sb, "-- Code generated by conduit via pg-schema-diff. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "-- conduit: %s\n", bi.Version())
	fmt.Fprintf(&sb, "-- pg-schema-diff: %s\n", bi.PGSchemaDiffVersion())
	sb.WriteString("\n")

	for i, stmt := range stmts {
		if i > 0 {
			sb.WriteString("\n")
		}

		sb.WriteString(stmt.ToSQL())
		sb.WriteString("\n")
	}

	if _, err := w.Write(sb.Bytes()); err != nil {
		return fmt.Errorf("failed to write output: %w", err)
	}

	return nil
}
